using System;
using System.Collections.Generic;
using System.IO;
using Manager.Core.Games.Models;
using Manager.Core.Models;

namespace Manager.Core.Games.Services
{
    public sealed class DoorstopConfigurationService
    {
        public void ConfigureModded(GameProfile profile, AppSettings settings, IEnumerable<string> assemblySearchPaths, Action<string> log)
        {
            if (profile == null || settings == null || !settings.IsGamePathValid)
                return;

            string gameDir = Path.GetDirectoryName(settings.GamePath);
            string dllSearchPath = BuildDllSearchPath(gameDir, assemblySearchPaths, log);
            string doorstopTargetRelative = ResolveDoorstopTargetRelative(profile, gameDir, log);
            string iniPath = Path.Combine(gameDir, profile.RuntimeLayout.DoorstopConfigFileName);

            List<string> ini = new List<string>();
            ini.Add("# Auto-generated by " + profile.ManagerTitle);
            ini.Add("[General]");
            ini.Add("enabled=true");
            ini.Add("target_assembly=" + doorstopTargetRelative);
            ini.Add("redirect_output_log=true");
            ini.Add("");
            ini.Add("[UnityMono]");
            ini.Add("dll_search_path_override=" + dllSearchPath);
            ini.Add("debug_enabled=false");
            ini.Add("debug_address=127.0.0.1:10000");
            ini.Add("debug_suspend=false");
            File.WriteAllLines(iniPath, ini.ToArray());

            if (log != null)
                log("Doorstop configured. target_assembly=" + doorstopTargetRelative);

            CopyProxyForGame(profile, settings.GamePath, log);
        }

        public void ConfigureVanilla(GameProfile profile, AppSettings settings)
        {
            if (profile == null || settings == null || !settings.IsGamePathValid)
                return;

            string gameDir = Path.GetDirectoryName(settings.GamePath);
            string doorstopConfigPath = Path.Combine(gameDir, profile.RuntimeLayout.DoorstopConfigFileName);
            string target = FirstDoorstopTargetCandidate(profile);

            List<string> lines = new List<string>();
            lines.Add("# Auto-generated by " + profile.ManagerTitle + " (Vanilla Mode)");
            lines.Add("[General]");
            lines.Add("enabled=false");
            lines.Add("target_assembly=" + target);
            File.WriteAllLines(doorstopConfigPath, lines.ToArray());
        }

        private static string BuildDllSearchPath(string gameDir, IEnumerable<string> assemblySearchPaths, Action<string> log)
        {
            HashSet<string> uniquePaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            if (assemblySearchPaths != null)
            {
                foreach (string path in assemblySearchPaths)
                {
                    if (!string.IsNullOrEmpty(path))
                        uniquePaths.Add(path);
                }
            }

            List<string> relativePaths = new List<string>();
            foreach (string path in uniquePaths)
            {
                try
                {
                    relativePaths.Add(GetRelativePath(gameDir, path));
                }
                catch (Exception ex)
                {
                    if (log != null)
                        log("Using absolute assembly search path for " + path + ": " + ex.Message);
                    relativePaths.Add(path);
                }
            }

            return string.Join(";", relativePaths.ToArray());
        }

        private static string ResolveDoorstopTargetRelative(GameProfile profile, string gameDir, Action<string> log)
        {
            string[] candidates = profile.RuntimeLayout.DoorstopTargetAssemblyRelativeCandidates ?? new string[0];
            for (int i = 0; i < candidates.Length; i++)
            {
                string relative = candidates[i];
                if (File.Exists(Path.Combine(gameDir, relative)))
                    return relative;
            }

            if (log != null)
                log("Doorstop target assembly missing. Launch may fail to load ModAPI.");

            return FirstDoorstopTargetCandidate(profile);
        }

        private static string FirstDoorstopTargetCandidate(GameProfile profile)
        {
            GameRuntimeLayout defaults = new GameRuntimeLayout();
            GameRuntimeLayout layout = profile != null && profile.RuntimeLayout != null
                ? profile.RuntimeLayout
                : defaults;
            string[] candidates = layout.DoorstopTargetAssemblyRelativeCandidates ?? new string[0];
            if (candidates.Length > 0)
                return candidates[0];

            string runtimeFolder = !string.IsNullOrEmpty(layout.RuntimeFolderName) ? layout.RuntimeFolderName : defaults.RuntimeFolderName;
            string binFolder = !string.IsNullOrEmpty(layout.BinFolderName) ? layout.BinFolderName : defaults.BinFolderName;
            return Path.Combine(runtimeFolder, Path.Combine(binFolder, "Doorstop.dll"));
        }

        private static void CopyProxyForGame(GameProfile profile, string gamePath, Action<string> log)
        {
            try
            {
                string gameDir = Path.GetDirectoryName(gamePath);
                string supportDir = profile.RuntimeLayout.GetDoorstopSupportPath(gameDir);
                string bitnessDir = DetectIsExe64Bit(gamePath) ? "x64" : "x32";
                string sourceProxy = Path.Combine(Path.Combine(supportDir, bitnessDir), profile.RuntimeLayout.DoorstopProxyDllName);
                string targetProxy = Path.Combine(gameDir, profile.RuntimeLayout.DoorstopProxyDllName);

                if (!File.Exists(sourceProxy))
                    return;

                File.Copy(sourceProxy, targetProxy, true);
                if (log != null)
                    log("Copied " + bitnessDir + " " + profile.RuntimeLayout.DoorstopProxyDllName);
            }
            catch (Exception ex)
            {
                if (log != null)
                    log("Doorstop proxy copy failed: " + ex.Message);
            }
        }

        private static string GetRelativePath(string fromPath, string toPath)
        {
            Uri fromUri = new Uri(fromPath.TrimEnd(Path.DirectorySeparatorChar) + Path.DirectorySeparatorChar);
            Uri toUri = new Uri(toPath);
            Uri relativeUri = fromUri.MakeRelativeUri(toUri);
            return Uri.UnescapeDataString(relativeUri.ToString().Replace('/', Path.DirectorySeparatorChar));
        }

        private static bool DetectIsExe64Bit(string exePath)
        {
            FileStream fs = null;
            BinaryReader br = null;
            try
            {
                fs = new FileStream(exePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
                br = new BinaryReader(fs);
                fs.Seek(0x3C, SeekOrigin.Begin);
                int peOffset = br.ReadInt32();
                fs.Seek(peOffset, SeekOrigin.Begin);
                uint peSignature = br.ReadUInt32();
                if (peSignature != 0x00004550)
                    return false;

                ushort machine = br.ReadUInt16();
                return machine == 0x8664;
            }
            catch
            {
                return false;
            }
            finally
            {
                if (br != null)
                    br.Close();
                if (fs != null)
                    fs.Close();
            }
        }
    }
}
