using System.Collections.Generic;
using System.IO;
using Manager.Core.Games.Models;
using Manager.Core.Models;

namespace Manager.Core.Games.Services
{
    public sealed class GameLaunchConfigurationService
    {
        public void WriteLaunchConfiguration(GameProfile profile, AppSettings settings)
        {
            if (profile == null || settings == null || !settings.IsGamePathValid)
                return;

            string gameDir = Path.GetDirectoryName(settings.GamePath);
            string binDir = profile.RuntimeLayout.GetBinPath(gameDir);
            if (!Directory.Exists(binDir))
                Directory.CreateDirectory(binDir);

            string iniPath = Path.Combine(binDir, "mod_manager.ini");
            List<string> lines = new List<string>();
            lines.Add("# Generated by Manager at launch");
            lines.Add("SelectedGameId=" + (settings.SelectedGameId ?? string.Empty));
            lines.Add("GamePath=" + (settings.GamePath ?? string.Empty));
            lines.Add("DarkMode=" + (settings.DarkMode ? "True" : "False"));
            lines.Add("DevMode=" + (settings.DevMode ? "True" : "False"));
            lines.Add("LogLevel=" + (settings.LogLevel ?? "Info"));
            lines.Add("IgnoreOrderChecks=" + (settings.IgnoreOrderChecks ? "True" : "False"));
            if (profile.SupportsSaveDiscovery)
            {
                lines.Add("AutoCondenseSaves=" + (settings.AutoCondenseSaves ?? "ask"));
                lines.Add("AutoLoadSaveSlot=" + settings.AutoLoadSaveSlot);
            }
            File.WriteAllLines(iniPath, lines.ToArray());
        }
    }
}
