<Project>
  <PropertyGroup>
    <GameInstallDir Condition="'$(GameInstallDir)' == ''">A:\SteamLibrary\steamapps\common\Paralives\</GameInstallDir>
    <GameManagedDir Condition="'$(GameManagedDir)' == ''">$(GameInstallDir)Paralives_Data\Managed\</GameManagedDir>
    <SmmHarmonyDll Condition="'$(SmmHarmonyDll)' == ''">$(MSBuildThisFileDirectory)mods\0Harmony\Assemblies\0Harmony.dll</SmmHarmonyDll>
  </PropertyGroup>
</Project>
