<Project>
  <PropertyGroup>
    <ShelteredInstallDir Condition="'$(ShelteredInstallDir)' == ''">A:\SteamLibrary\steamapps\common\Sheltered\</ShelteredInstallDir>
    <ShelteredManagedDir Condition="'$(ShelteredManagedDir)' == ''">$(ShelteredInstallDir)Sheltered_Data\Managed\</ShelteredManagedDir>
    <SmmHarmonyDll Condition="'$(SmmHarmonyDll)' == ''">$(MSBuildThisFileDirectory)mods\0Harmony\Assemblies\0Harmony.dll</SmmHarmonyDll>
  </PropertyGroup>
</Project>
